### PR TITLE
Fix implicit any

### PR DESCRIPTION
**Pull request by fraparisi**
If typescript is configured for "noImplicitAny" the older types generate error in compilation.

### CODE REVIEW

**Comment by fraparisi** [comment]
@f now should be fine :)

**Comment by yoyoys** [comment]
I think `waitFor` can be a generic.

**Comment by fraparisi** [comment]
@yoyoys updated thanks.

**Comment by brantwills** [comment]
Ran into this myself today - many thanks for addressing and all the work put into vue-wait!

**Comment by fraparisi** [comment]
@f any news on this?
Thanks in advance

**Pull request merged**
